/* eslint-disable no-unused-vars */
import { redirect } from "react-router-dom";
import Button from "../components/Button";
import { useEffect, useState } from "react";
import Navbar from "../components/Navbar";
import Hyperlink from "../components/Hyperlink";

const PrivacyPolicy = () => {
  const [name, setName] = useState("");

  return (
    <div className="bg-slate-900 p-3 flex justify-center items-center pb-36">
      <Navbar></Navbar>
      <div className="max-w-2xl">
        {/* PRIVACY POLICY */}
        <h1 className="text-white text-right text-xl font-montserrat font-bold mb-8">
          Privacy Policy
        </h1>
        <p className="text-white text-sm font-lato">
          Last updated: August 27, 2024 This Privacy Policy describes Our
          policies and procedures on the collection, use and disclosure of Your
          information when You use the Service and tells You about Your privacy
          rights and how the law protects You. We use Your Personal data to
          provide and improve the Service. By using the Service, You agree to
          the collection and use of information in accordance with this Privacy
          Policy.
        </p>

        {/* INTERCEPTION AND DEFINITION */}
        <h1 className="text-white text-left text-xl font-montserrat font-bold mt-16 mb-8">
          Interpretation and Definitions
        </h1>
        <h2 className="text-white text-left text-lg font-montserrat font-semibold my-1">
          Interpretation
        </h2>
        <p className="text-white text-sm font-lato">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>
        <h2 className="text-white text-left text-lg font-montserrat font-semibold mt-8 mb-1">
          Definitions
        </h2>
        <p className="text-white text-sm font-lato">
          For the purposes of this Privacy Policy:
        </p>
        <ul className="list-disc list-inside text-sm">
          <li className="text-white font-lato">
            <span className="font-bold">Account</span> means a unique account
            created for You to access our Service or parts of our Service.
          </li>
          <li className="text-white font-lato">
            <span className="font-bold">Affiliate</span> means an entity that
            controls, is controlled by or is under common control with a party,
            where &quot;control&quot; means ownership of 50% or more of the
            shares, equity interest or other securities entitled to vote for
            election of directors or other managing authority.
          </li>
          <li className="text-white font-lato">
            <span className="font-bold">
              &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this
              Agreement
            </span>{" "}
            refers to Meify.
          </li>
          <li className="text-white font-lato">
            <span className="font-bold">Third-party Social Media Service</span>{" "}
            refers to any website or any social network website through which a
            User can log in or create an account to use the Service.
          </li>
          <li className="text-white font-lato">
            <span className="font-bold">Usage Data</span> refers to data
            collected automatically, either generated by the use of the Service
            or from the Service infrastructure itself (for example, the duration
            of a page visit).
          </li>
          <li className="text-white font-lato">
            <span className="font-bold">You</span> means the individual
            accessing or using the Service, or the company, or other legal
            entity on behalf of which such individual is accessing or using the
            Service, as applicable.
          </li>
        </ul>

        {/* COLLECTING PERSONAL DATA */}
        <h1 className="text-white text-left text-xl font-montserrat font-bold mt-16 mb-8">
          Collecting and Using Your Personal Data
        </h1>
        <h2 className="text-white text-left text-lg font-montserrat font-semibold mt-8 mb-1">
          Types of Data Collected
        </h2>
        <h3 className="text-white text-left text-md font-montserrat mt-5 mb-1">
          Personal Data
        </h3>
        <p className="text-white text-sm font-lato">
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to: Usage Data
        </p>
        <h3 className="text-white text-left text-md font-montserrat mt-5 mb-1">
          Usage Data
        </h3>
        <p className="text-white text-sm font-lato">
          Usage Data is collected automatically when using the Service. Usage
          Data may include information such as Your Device&apos;s Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that You visit, the time and date of Your visit,
          the time spent on those pages, unique device identifiers and other
          diagnostic data. When You access the Service by or through a mobile
          device, We may collect certain information automatically, including,
          but not limited to, the type of mobile device You use, Your mobile
          device unique ID, the IP address of Your mobile device, Your mobile
          operating system, the type of mobile Internet browser You use, unique
          device identifiers and other diagnostic data. We may also collect
          information that Your browser sends whenever You visit our Service or
          when You access the Service by or through a mobile device. We use
          Spotify API to to show data your account and then show your currently
          playing. You will be able to see which music we are going to shown in
          our website.
        </p>
        <h3 className="text-white text-left text-md font-montserrat mt-5 mb-1">
          Information from Third-Party Social Media Services
        </h3>
        <p className="text-white text-sm font-lato">
          The Company allows You to create an account and log in to use the
          Service through the following Third-party Social Media Services:
          Spotify
        </p>
        <h3 className="text-white text-left text-md font-montserrat mt-5 mb-1">
          Security of Your Personal Data
        </h3>
        <p className="text-white text-sm font-lato">
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect Your Personal Data, We cannot guarantee
          its absolute security.
        </p>

        {/* CHILDREN PRIVACY */}
        <h1 className="text-white text-left text-xl font-montserrat font-bold mt-16 mb-8">
          Children&apos;s Privacy
        </h1>
        <p className="text-white text-sm font-lato">
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If You are a parent or guardian and You are aware
          that Your child has provided Us with Personal Data, please contact Us.
          If We become aware that We have collected Personal Data from anyone
          under the age of 13 without verification of parental consent, We take
          steps to remove that information from Our servers. If We need to rely
          on consent as a legal basis for processing Your information and Your
          country requires consent from a parent, We may require Your
          parent&apos;s consent before We collect and use that information.
        </p>

        {/* LINK TO OTHER WEB */}
        <h1 className="text-white text-left text-xl font-montserrat font-bold mt-16 mb-8">
          Links to Other Websites
        </h1>
        <p className="text-white text-sm font-lato">
          Our Service may contain links to other websites that are not operated
          by Us. If You click on a third party link, You will be directed to
          that third party&apos;s site. We strongly advise You to review the
          Privacy Policy of every site You visit. We have no control over and
          assume no responsibility for the content, privacy policies or
          practices of any third party sites or services.
        </p>

        {/* CHANGES TO THIS PRIVACY POLICY */}
        <h1 className="text-white text-left text-xl font-montserrat font-bold mt-16 mb-8">
          Changes to this Privacy Policy
        </h1>
        <p className="text-white text-sm font-lato">
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page. We will
          let You know via email and/or a prominent notice on Our Service, prior
          to the change becoming effective and update the &quot;Last
          updated&quot; date at the top of this Privacy Policy. You are advised
          to review this Privacy Policy periodically for any changes. Changes to
          this Privacy Policy are effective when they are posted on this page.
        </p>

        {/* CONTACT ME/US */}
        <h1 className="text-white text-left text-xl font-montserrat font-bold mt-16 mb-8">
          Contact Me or Us
        </h1>
        <p className="text-white text-sm font-lato">
          If you have any questions about this Privacy Policy, You can contact
          us By Instagram:{" "}
          <a
            href="https://instagram.com/vyanzll"
            target="_blank"
            rel="noreferrer"
            className="text-blue-600"
          >
            [Email Protected]
          </a>
        </p>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
